### Create Store
POST http://localhost:3000/store
Content-Type: application/json

{
  "fullName": "Lili",
  "cnpj": "12345678913420",
  "email": "Lili@realstate.com",
  "password": "{{ $random.alphanumeric(10) }}"
}

### Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "fullName": "Gilvannia",
  "cpf": "43243543581",
  "email": "gi@oab.com.br",
  "password": "12345678910"
}

###
GET http://localhost:3000/store

###
GET http://localhost:3000/user