### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "chewbacca@petshop.com",
  "password": "17645678910"
}


### Create Store
POST http://localhost:3000/store
Content-Type: application/json

{
  "fullName": "chewbacca",
  "cnpj": "55545678911287",
  "email": "chewbacca@petshop.com",
  "password": "17645678910"
}

### Create User
POST http://localhost:3000/user
Content-Type: application/json

{
  "fullName": "DiogoCampos",
  "cpf": "46643543573",
  "email": "diogocamp@crecisp.org.br",
  "password": "17645678910"
}

###
POST http://localhost:3000/transfer
Content-Type: application/json

{
  "amount": 100,
  "payerId": "9fe29330-d012-4f26-a7ad-07bb420d3513",
  "payeeId": "d02ae711-fd7c-41e3-ba6b-ea956ccb4aa4"
}

###
GET http://localhost:3000/user/9fe29330-d012-4f26-a7ad-07bb420d3513
Content-Type: application/json

###
GET http://localhost:3000/store/d02ae711-fd7c-41e3-ba6b-ea956ccb4aa4
Content-Type: application/json

###
GET http://localhost:3000/user


